opennms:
  local:
    baseurl: http://localhost:8980/opennms
    username: admin
    password: admin
zones:
  mousebar:
    world: "world"
    x: 0.000
    y: 0.000
    z: 0.000
    radius: 1.000
    height: 1.000
  test:
    world: "world"
    x: 156.98
    y: 63.000
    z: -114.068
    radius: 2.000
    height: 4.000
