name: mc2nms
version: ${project.version}
main: org.opennms.mc2nms.MinecraftPlugin
api-version: "1.15"
authors: [x_intercept]
description: Generate OpenNMS events from player activity

commands:
  getzones:
    description: Return the list of tracked zones