---
version: '3'

volumes:
  data-mc-forge: {}

services:
  mc:
    image: itzg/minecraft-server
    container_name: mc
    environment:
      TZ: "America/New_York"
      EULA: "TRUE"
      TYPE: SPIGOT
      VERSION: "1.15.2"
    volumes:
      - data-mc-forge:/data
      - ./plugins:/plugins:ro
      - ./mods:/mods:ro
      - ./server.properties:/data/server.properties
    ports:
      - "25565:25565/tcp"
      - "25575:25575/tcp"
